//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTime.ServiceClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDateTimeService")]
    public interface IDateTimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeService/FindDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeService/FindDayOfWeekResponse")]
        string FindDayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateTimeService/FindDayOfWeek", ReplyAction="http://tempuri.org/IDateTimeService/FindDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> FindDayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDateTimeServiceChannel : DateTime.ServiceClient.ServiceReference.IDateTimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateTimeServiceClient : System.ServiceModel.ClientBase<DateTime.ServiceClient.ServiceReference.IDateTimeService>, DateTime.ServiceClient.ServiceReference.IDateTimeService {
        
        public DateTimeServiceClient() {
        }
        
        public DateTimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DateTimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateTimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FindDayOfWeek(System.DateTime date) {
            return base.Channel.FindDayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> FindDayOfWeekAsync(System.DateTime date) {
            return base.Channel.FindDayOfWeekAsync(date);
        }
    }
}
